FROM golang:1.24.3 AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y make libunbound-dev

COPY . .

RUN make build-resolver

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  libunbound8 \
  ca-certificates && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/bin/resolver /app/resolver


ENTRYPOINT ["/app/resolver"]