version: '3.8'

services:
  resolver:
    build:
      context: ..
      dockerfile: local/Dockerfile.resolver
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - BEACON_ETCD_ENDPOINTS=http://etcd:2379
      - BEACON_RESOLVER_TYPE=recursive
      - BEACON_FORWARDER=1.1.1.1
    depends_on:
      - etcd
    networks:
      - beacondns

  controller:
    build:
      context: ..
      dockerfile: local/Dockerfile.controller
    ports:
      - "8080:8080"
    environment:
      - BEACON_CONTROLLER_PORT=8080
      - BEACON_DB_HOST=postgres
      - BEACON_DB_NAME=beacon_db
      - BEACON_DB_USER=beacon
      - BEACON_DB_PASSWORD=password
      - BEACON_DB_PORT=5432
      - BEACON_ETCD_ENDPOINTS=http://etcd:2379
    depends_on:
      - etcd
      - migrate
    networks:
      - beacondns

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=beacon
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=beacon_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beacon -d beacon_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - beacondns
  
  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../migrations:/migrations
    command: 
      - "-path=/migrations"
      - "-database=postgres://beacon:password@postgres:5432/beacon_db?sslmode=disable"
      - "up"
    networks:
      - beacondns

  etcd:
    image: quay.io/coreos/etcd:v3.5.10
    ports:
      - "2379:2379"
      - "2380:2380"
    command: etcd -advertise-client-urls http://etcd:2379 -listen-client-urls http://0.0.0.0:2379
    volumes:
      - etcd_data:/etcd-data
    networks:
      - beacondns

networks:
  beacondns:
    driver: bridge

volumes:
  postgres_data:
  etcd_data:
