FROM golang:1.24.3 AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y make

COPY . .

RUN make build-resolver

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/bin/resolver /app/resolver


ENTRYPOINT ["/app/resolver"]