FROM golang:1.24-bookworm

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN make build-controller

FROM debian:bookworm-slim

COPY --from=builder /app/bin/controller /usr/local/bin/controller

ENTRYPOINT ["controller"]
