FROM golang:1.24-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN make build-resolver

FROM debian:bookworm-slim 

COPY --from=builder /app/bin/resolver /usr/local/bin/resolver

ENTRYPOINT ["resolver"]
